name: Test Content Guardian (Local)
on:
  workflow_dispatch:
  push:
    paths:
      - "testdata/**"
      - "src/**"
      - "action.yml"

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run local action
        uses: ./
        with:
          markup_ai_api_key: ${{ secrets.MARKUP_AI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dialect: "american_english"
          style-guide: "ap"
          # tone: "formal"
          strict_mode: "false"
